name: Deploy main
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Make envfile
        uses: ozaytsev86/create-env-file@v1
        with:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          APP_REGION: ${{ secrets.APP_REGION }}
          S3_BUCKET: ${{ secrets.S3_BUCKET }}


      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: ${{ secrets.APP_NAME }}
          environment_name: ${{ secrets.APP_ENVIRONMENT_NAME }}
          version_label: "ver-${{ github.sha }}"
          region: ${{ secrets.APP_REGION }}
          deployment_package: deploy.zip
