name: Deploy master
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: AKIAQRFQB7N4SPWHPACV
          aws_secret_key: 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
          application_name: api
          environment_name: api-env
          version_label: 12345
          region: ap-southest-1
          deployment_package: deploy.zip
